# Generated by Django 3.1.5 on 2021-01-12 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20210112_1103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees',
            old_name='Mot_pass',
            new_name='mpp',
        ),
    ]
