# Generated by Django 3.1.5 on 2021-01-13 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20210112_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='CHAMBRE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('res_id', models.IntegerField()),
                ('Client_id', models.IntegerField()),
                ('Num_chambre', models.IntegerField()),
                ('nameChambre', models.CharField(max_length=200)),
                ('libre', models.CharField(max_length=1)),
            ],
        ),
    ]
