# Generated by Django 3.1.5 on 2021-01-14 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_chambre'),
    ]

    operations = [
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=100)),
                ('CIN', models.CharField(max_length=50)),
                ('DATE_DEL', models.DateTimeField()),
                ('ADRESSE', models.CharField(max_length=200)),
                ('mpp', models.CharField(max_length=100)),
                ('emp_id', models.IntegerField()),
            ],
        ),
    ]
