from django.urls import path
from . import views

urlpatterns = [
    path('', views.employeesList, name="employees"),
    path('listemp', views.employeesList, name="employees"),
    path('detail/<str:pk>/', views.employeesdetail, name="detail"),
    path('create', views.employeesCreate, name="create"),
    path('update/<str:pk>/', views.employeesupdate, name="update"),
    path('delete/<str:pk>/', views.employeesdelete, name="delete"),
    path('listreserv', views.reservationList, name="reservation"),
    path('detailreserv/<str:pk>/', views.reservationdetail, name="detailr"),
    path('createreserv', views.reservationCreate, name="create"),
    path('updatereserv/<str:pk>/', views.reservationupdate, name="updater"),
    path('deletereserv/<str:pk>/', views.reservationdelete, name="deleter"),
    path('listarr', views.arriveelist, name="arrivee"),
    path('detailrarr/<str:pk>/', views.arriveedetail, name="detaila"),
    path('createarr', views.arriveeCreate, name="createa"),
    path('updatearr/<str:pk>/', views.arriveeupdate, name="updatea"),
    path('deletearr/<str:pk>/', views.arriveedelete, name="deletea"),
    path('triearr/<str:debut>/<str:fin>/', views.arriveetrier, name="arrrang"),
    path('listdep', views.departlist, name="depart"),
    path('detaildep/<str:pk>/', views.departdetail, name="detaildep"),
    path('createdep', views.departCreate, name="createdep"),
    path('updatedep/<str:pk>/', views.departupdate, name="updatedep"),
    path('deletedep/<str:pk>/', views.departdelete, name="deletea"),
    path('triedep/<str:debut>/<str:fin>/', views.departtrier, name="arrrang"),
    path('listhors', views.horsservicelist, name="horsservice"),
    path('detailhors/<str:pk>/', views.horsservicedetail, name="detailhors"),
    path('createhors', views.horsservicecreate, name="createdehors"),
    path('updatehors/<str:pk>/', views.horsserviceupdate, name="updatehors"),
    path('deletehors/<str:pk>/', views.horsservicedelete, name="deletea"),
    path('triehors/<str:debut>/<str:fin>/', views.horsservicetrier, name="arrrang"),
    path('listchambre', views.chambretlist, name="chambre"),
    path('detailchambre/<str:pk>/', views.chambredetail, name="detailhors"),
    path('createchambre', views.chambrecreate, name="createdehors"),
    path('updatechambre/<str:pk>/', views.chambreupdate, name="updatehors"),
    path('deletechambre/<str:pk>/', views.chambredelete, name="deletea"),
    path('listeclient', views.clientList, name="employees"),
    path('detailclient/<str:pk>/', views.clientdetail, name="detail"),
    path('createclient', views.clientCreate, name="create"),
    path('updateclient/<str:pk>/', views.clientupdate, name="update"),
    path('deleteclient/<str:pk>/', views.clientdelete, name="delete"),
    ]
